ATV-1077: Fix double press close/back button to stop playback
picasso-one/betterplayer-fork pull request #23
Opened 2024-06-05 13:38 UTC by RBajor

2024-06-05 15:20 UTC, MJablonskiCodespot commented on lib/src/video_player/video_player.dart
> +    // _timer?.cancel();
comment?

2024-06-05 15:27 UTC, MJablonskiCodespot requested changes
mamy  juz funkcje on exit clicked ktora robi defacto to samo  - zamiast tworzyc nowa funkcje, zobacyzlbym czemu tamta nie dziala

2024-06-05 18:52 UTC, RBajor commented on lib/src/video_player/video_player.dart
> +    // _timer?.cancel();
my mistake, it shouldn't be in comment

2024-06-06 06:54 UTC, RBajor commented
PRka do zamknięcia, niepotrzebna implementacja w better player gdyż nasz custom controller ogarnia juz to

2024-06-06 06:54 UTC, closed without merging